name: Start cluster
on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * 1-5'
    
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: git pull
    - run: pip install -r requirements.txt
    - run: mkdir -p ./stats
    - run: python github_stats/scrape.py

    # Commit and push all changed files.
    - name: Update stats
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        git add stats
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push origin master --force