name: Start cluster
on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * 1-5'
    
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -U pip && pip install databricks-cli
    - run: |
        databricks configure --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN
        databricks clusters start --cluster-id $CLUSTER_ID